### ISSUE TITLE
XmlRepository class(es) missing from the nuget package?

### ISSUE THREAD

**Issue by vurso** [SharpRepository/SharpRepository#138]
Hi,

Downloaded the SharpRepository nuget pacakge and it seems the XmlRepository is nonexistent in this assembly (or am I just going about it the wrong way)?

I could do with some pointers on how to use the Xml data source part which is really why I wanted to use this awesome library (and it would save me a lot of coffee trips).

Cheers,

T

**Comment by jtreuting** [comment]
The XmlRepository is here: http://www.nuget.org/packages/SharpRepository.XmlRepository/1.3.5.18-unstable


It is marked as pre-release only because it hasn't been used a lot in the real world (as far as I can tell).  I've used it for simple things like storing a small amount of data for simple desktop apps, etc.


It is meant to be used with POCO objects and will store the collection of objects in a single XML file (1 per repository type).  It is not meant to be used for querying existing random XML files, so if that is your purpose then it won't work for you.


Jeff


________________________________

**Comment by vurso** [comment]
Thank you for the clarification Jeff, that makes sense.

Yes I gathered that after looking into the requirements some more so going to just wire up my own XML data provider that SharpRepository can work with (or anything else).

Cheers,

T
