### ISSUE TITLE
Factory doesn't returns all ICompoundKeyRepositories

### ISSUE THREAD

**Issue by fiorebat** [SharpRepository/SharpRepository#139]
Factory don't returns ICompoundKeyRepository&lt;T> and  ICompoundRepository&lt;MT,Tkey, Tkey2, Tkey3> that are implemented repositories!

Regards!

**Comment by jtreuting** [comment]
Can you give me some more information on what the problem is you are having? What version are you using? Some code examples of what you are trying to do would be helpful as well.


Thanks,


Jeff

________________________________

**Comment by fiorebat** [comment]
i'm using latest from nuget, 1.4.6.15


this code is valid: 

ICompoundRepository<MyModel, int, int, int> myRepo1 = new EfRepository<MyModel, int, int, int>(dbContext);
ICompoundRepository<MyModel> myRepo2 = new InMemoryRepository<MyModel>();

i cannot obtain this code using factory

ICompoundRepository<MyModel, int, int, int> myRepo1 = RepositoryFactory.GetInstance<MyModel, int, int, int>();
ICompoundRepository<MyModel> myRepo2 = RepositoryFactory.GetInstance<MyModel>();

I write from memory, hope is correct

Tnx!!

**Comment by jtreuting** [comment]
There is only a method on the RepositoryFactory for creating an ICompoundRepository<T, TKey, TKey2> and not anything with more than 2 keys.

I'd be happy to accept a PR that adds that.

**Comment by fiorebat** [comment]
Your project causes some headache, nUnit has some performance issues, some time loads for 2-3 minutes.. nUnit test adapter site  in fact says "Startup performance is now improved as compared to the developer preview, but is still intermittently slow."

Do you have same times?

**Comment by jtreuting** [comment]
If you are running the integration tests, then yes they can take some time to run. They are running against actual instances of various data stores. If you don't have those configured then it also might be timing out while connecting. I don't believe it is due to start up times of nUnit.


Jeff Treuting
Director of Software Delivery

[http://www.fairwaytech.com/media/fairway-logo.gif]
Fairway Technologies Inc. | Our People, Your Solution.®

[http://www.fairwaytech.com/media/phone-icon.gif]  (858) 454-4471 x209
[http://www.fairwaytech.com/media/cell-icon.gif]  (310) 428-5426

fairwaytech.com<http://www.fairwaytech.com/> | [http://www.fairwaytech.com/media/tiny-linkedin.gif] <http://www.linkedin.com/company/fairway-technologies>  [http://www.fairwaytech.com/media/icon-twitter.gif] <http://twitter.com/FairwayTech>  [http://www.fairwaytech.com/media/tiny-facebook.gif] <http://www.facebook.com/pages/Fairway-Technologies/127195970658682>  [http://www.fairwaytech.com/media/tiny-rss.gif]

________________________________

**Comment by fiorebat** [comment]
I did the PR https://github.com/SharpRepository/SharpRepository/pull/143

Project startup takes 6 minutes discovery tests.. I don't think during discovery he connects against datasources...

Just for completion, test execution takes 6 minutes too :)

Regards!

**Comment by fiorebat** [comment]
Just for completion, test execution takes less than a minute with MongoDB and CouchDB running in background. It's a bit slow, but match better
