### ISSUE TITLE
An entity object cannot be referenced by multiple instances of IEntityChangeTracker

### ISSUE THREAD

**Issue by behzad888** [SharpRepository/SharpRepository#141]
When use :
CategoryDomain relation into PostDomain , in added post item
see error in Ef5RepositoryBase.cs ln 41.
thats error is 'An entity object cannot be referenced by multiple instances of IEntityChangeTracker 'when proxyConfiguration disable and see 'Violation of PRIMARY KEY constraint ' error when proxyConfiguration enabled

**Comment by jtreuting** [comment]
Without seeing code or your configuration, my guess is that you are not setting SharpRepository up to share a DbContext between all the repositories so it is using new ones each time and you have 2 repositories with 2 DbContexts tracking the same entity.  Again this is a guess since I don't have more info.

Here is some more info on how to set that up.  Basically you have to tell SharpRepository what IoC container to use so it knows where to get a DbContext from, and then you have to configure your IoC to use the same DbContext per request.

http://stackoverflow.com/questions/15273074/sharprepository-ef5-how-to-share-dbcontext

http://fairwaytech.com/2013/02/sharprepository-configuration/

**Comment by jtreuting** [comment]
Since I haven' heard anything back, I'm going to close this.
