### ISSUE TITLE
The new InMemoryRepository throws System.NotImplementedException on CompoundKeyRepository GetAll() method

### ISSUE THREAD

**Issue by fiorebat** [SharpRepository/SharpRepository#147]
I'm testing new version of package.

I have found a bug only in InMemoryRepository!
EfRepository works.

I think you broke something merging

```
Result StackTrace:	
in SharpRepository.Repository.CompoundKeyRepositoryBase`1.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy)
   in SharpRepository.Repository.CompoundKeyRepositoryBase`1.GetAll()
threw exception: System.NotImplementedException

```

using my original branch for the last PR I don't have this problem

**Comment by jtreuting** [comment]
Oops, I ran the unit tests but forgot to run the integration tests because I don't have all the data stores setup on my new machine yet.  Just ran the integration tests for the InMemory and the problem is that the new method that has the overloads for include paths is getting called internally instead of the method that seems like it should be called.  And since InMemory doesn't have the concept of include paths, those methods are left as NotImplemented.

So the solution is to figure out how to make sure the proper method is called instead of the one with the include path parameters.  Or implement the methods but basically ignore the include params passed in.  I'll look at this now and see which makes more sense and works.

**Comment by jtreuting** [comment]
I've uploaded InMemory (and EfRepository) 1.4.7.1 that fixes the issue with the GetAll for CompoundKeyRepository implementations.  Please let me know that it worked (or didn't).

Thanks.

**Comment by fiorebat** [comment]
I'm sorry, but nothing changed with that upgrade..

**Comment by jtreuting** [comment]
The integration tests are fixed with the changes that were made.  It seems like maybe the nuget package didn't get the updated DLL possibly.  I recreated it and submitted it as a prerelease so you could verify if it fixes the issue.  https://www.nuget.org/packages/SharpRepository.InMemoryRepository/1.4.7.2-beta

**Comment by fiorebat** [comment]
Still not working. I try to debug it for you in this days

**Comment by fiorebat** [comment]
the problem is in SharpRepository.Repository, not in SharpRepository.InMemoryRepository

I replaced Nuget SharpRepository.Repository.dll with last master branch compiled and it works.

And it's quite obvious, you edited SharpRepository.Repository/CompoundKeyRepositoryBase.cs..

no?

**Comment by jtreuting** [comment]
Sorry, I'm losing my mind.  I used to have an automated process handle the nuget packaging and I missed the most obvious thing here.

I just uploaded 1.4.7.2 of SharpRepository.Repository and InMemoryRepository and EfRepository.  The later 2 have a requirement of 1.4.7.2 for the main Repository package so it will need to update the core package

**Comment by fiorebat** [comment]
Yeeee, it's finally ok!!!

Thanks
