### ISSUE TITLE
InMemoryRepository not returns elements of inherited type

### ISSUE THREAD

**Issue by evgenykorobets** [SharpRepository/SharpRepository#168]
Not returns elements of inherited type from InMemoryRepository of parent type.
```
public class Parent
{
  public int Id { get; set; }
}

public class Child : Parent
{
}

public void TestMethod()
{
  var repo = new InMemoryRepository<Parent, int>();
  repo.Add(new Child());
  var childs = repo.GetAll().OfType<Child>().ToArray();
}
```

**Comment by omarpiani** [comment]
Hi @evgenykorobets , I put my hands on this.
InMemory uses ConcurrentDictionary collection type that behaves how you will.

In next days I will search if there is a workaround for you.

Regards

**Comment by omarpiani** [comment]
https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.InMemoryRepository/InMemoryRepositoryBase.cs#L32 the CloneDictionary method reinstantiate all items during a query.

I think was done in order to permit the Join between different repositories.
You can substitute line https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.InMemoryRepository/InMemoryRepositoryBase.cs#L21 with `return _items;` if you want to take a test.

**Comment by evgenykorobets** [comment]
Thanks for the answer.
