### ISSUE TITLE
Using pure .net core DI without StructureMap

### ISSUE THREAD

**Issue by xxsybreedxx** [SharpRepository/SharpRepository#191]
Hi, is it possible to use only .net core di container, without support of StructureMap?

**Comment by omarpiani** [comment]
Hi, unfortunatelly not.. I worked to find a solution with a factory that covers all repositories but the problem is this:
https://github.com/aspnet/DependencyInjection/issues/474 
"Closing because we are not planning on adding this feature to the default DI container."

You can easily and well use microsoft DI to configure a single repository like in https://github.com/SharpRepository/SharpRepository/wiki/Custom-Repositories
