### ISSUE TITLE
How can I execute mongodb $text index queries?

### ISSUE THREAD

**Issue by svncsvr** [SharpRepository/SharpRepository#219]
Is is possible to execute mongo db $text queries or include it in sharp repository query pipeline?

**Comment by omarpiani** [comment]
SharpRepository can't full text search, add full text search well be great but at the moment is really painfull, because implementation is different for every database driver.

In MongoDb C# Driver you can fulltext search with:

```
var filter = Builders<OrderExtension>.Filter.Text("text");
cli.GetDatabase("test").GetCollection<OrderExtension>("OrderExtension").Find(filter).ToList();
```

I really appreciate any support in order to implement this in our system!
