### ISSUE TITLE
.NET 5 DI/AutoFac Issue

### ISSUE THREAD

**Issue by attiqeurrehman** [SharpRepository/SharpRepository#251]
Hi, 

I am trying to setup it for .net5 not sure f it's supported but I followed instruction found under [ASP.NET Core 3.0 
](https://github.com/SharpRepository/SharpRepository/wiki/Getting-started#aspnet-core-30-applications) but getting the exception. 

Following are the exception details:

```
System.TypeLoadException: Method 'RegistrationsFor' in type 'SharpRepository.Ioc.Autofac.RepositoryRegistrationSource' from assembly 'SharpRepository.Ioc.Autofac, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at SharpRepository.Ioc.Autofac.AutofacExtensions.RegisterSharpRepository(ContainerBuilder containerBuilder, ISharpRepositoryConfiguration configuration, String repositoryName, Object[] lifetimeScopeTag)

   at SharpRepository.Ioc.Autofac.AutofacExtensions.RegisterSharpRepository(ContainerBuilder containerBuilder, IConfigurationSection configurationSection, String repositoryName, Object[] lifetimeScopeTag)
```

**Comment by omarpiani** [comment]
Hi, I never tested with .net5, but in teory all new .net implementations are backwards compatible, I'll test it, but I need at least 1 week.

**Comment by attiqeurrehman** [comment]
@omarpiani any update on this?

**Comment by omarpiani** [comment]
you wrote with perfect timing, I take a look now

**Comment by omarpiani** [comment]
ok, I pushed a .net5 sample here: https://github.com/SharpRepository/SharpRepository/tree/sample/net5/SharpRepository.Samples.net5Mvc

the problem is in `autofac` 6, that is required by `Autofac.Extensions.DependencyInjection` 7. Downgrade it to 6 to get project work.

For sure I need the new nuget key from @jtreuting  to update `SharpRepository.Ioc.AutoFac` package able to run autofac 6

**Comment by omarpiani** [comment]
nuget released
