### ISSUE TITLE
Project Logo! :)

### ISSUE THREAD

**Issue by bgriswold** [SharpRepository/SharpRepository#4]

**Comment by omarpiani** [comment]
@katiacoppo is doing a logo right now for me 😃

**Comment by omarpiani** [comment]
![sharprepository_logo-06](https://cloud.githubusercontent.com/assets/2690653/26342225/79903c5e-3f97-11e7-810b-8bd77ddb4ac3.png)

This is a preview.. I will use for NuGet 1.5.0-prerelease 's

**Comment by katiacoppo** [comment]
There are also these versions.
![sharprepository_logo-02](https://cloud.githubusercontent.com/assets/6349515/26343409/323246ae-3f9c-11e7-9578-b40447965abe.png)
![sharprepository_logo-08](https://cloud.githubusercontent.com/assets/6349515/26343410/32336750-3f9c-11e7-8ff6-89c8376cd2df.png)

**Comment by omarpiani** [comment]
@jtreuting,  @bgriswold and why not @eloekset, which one you will chose? Have you got some request for @katiacoppo ?

For the moment I choosed the first one, that i put in nuget packages.
https://www.nuget.org/packages/SharpRepository.Repository/1.5.0.1-prerelease

After that please add the logo to https://github.com/SharpRepository.

**Comment by eloekset** [comment]
I agree, the chosen one is the best.

**Comment by jtreuting** [comment]
I kinda like the last one with the straight lines in the hash that is not touching the bottom.  But i think either one works for me.  Exciting!

**Comment by bgriswold** [comment]
Personally, I prefer the latter as well. Is the purple and black indicative of the Visual Studio brand?

**Comment by omarpiani** [comment]
Ok, the maintainers wins 🥇 

@katiacoppo  can you provide the logo with transpartent background, I think you can reduce the empty space around logo.

**Comment by jtreuting** [comment]
Thanks for putting this together @katiacoppo !!

**Comment by katiacoppo** [comment]
Thanks to all of you!

Yes, C# hasn’t a logo, but if you take a look on the web [](http://bit.ly/2qj5MTj) there are a lot of violet concept logos for C#. That violet is the Visual Studio’s violet of course! :)

Give me a little more time to remove some imperfections end export it with transparent background.

**Comment by katiacoppo** [comment]
![sharprepository_logo_def-01](https://user-images.githubusercontent.com/6349515/28491139-7b5ce84c-6eeb-11e7-8f84-ec1fc33a6872.png)
![sharprepository_logo_def-02](https://user-images.githubusercontent.com/6349515/28491140-7b5e9034-6eeb-11e7-9d10-7a0647772331.png)
![sharprepository_logo_def-03](https://user-images.githubusercontent.com/6349515/28491142-7b6350c4-6eeb-11e7-9c5b-e3b8ef1e73b8.png)
![sharprepository_logo_def-04](https://user-images.githubusercontent.com/6349515/28491141-7b600e46-6eeb-11e7-8c4c-d6139479c18e.png)

Excuse me, it's been so long since I've had written my last comment.
Which do you prefer: the original logo, the one with trasparency or the one with shadow?
I have created also a version with the extended name.

**Comment by omarpiani** [comment]
in https://github.com/SharpRepository/SharpRepository, from README.md is simply awesome

**Comment by omarpiani** [comment]
@jtreuting  or @bgriswold , we need to put logo in https://github.com/SharpRepository team

**Comment by omarpiani** [comment]
👍
